pal_loader: Print clearer error on invalid invocations

diff --git a/Runtime/pal_loader b/Runtime/pal_loader
--- a/Runtime/pal_loader
+++ b/Runtime/pal_loader
@@ -67,7 +67,7 @@ else
     SGX=@SGX@
 fi
 
-MANIFEST=
+APPLICATION=
 ENVS=()
 PREFIX=()
 
@@ -97,8 +97,8 @@ fi
 
 while [ "$1" != "" ];
 do
-	if [ "$MANIFEST" == "" ]; then
-		MANIFEST=$1
+	if [ "$APPLICATION" == "" ]; then
+		APPLICATION=$1
 		shift
 		continue
 	fi
@@ -106,9 +106,23 @@ do
 	break
 done
 
-if [ "$MANIFEST" == "" ]; then
+if [ "$APPLICATION" == "" ]; then
 	echo "Usage: $0 [<application>] <args>..."
 	exit 1
+fi
+
+if [ "$SGX" == "1" ] && [ ! -e "$APPLICATION.manifest.sgx" ]; then
+    echo -n "Invalid application path specified ($APPLICATION.manifest.sgx does not exist). "
+    echo -n "The path should point to application configuration files, so that they can be found "
+    echo    "after appending corresponding extensions."
+    exit 1
+fi
+
+if [ ! "$SGX" == "1" ] && [ ! -e "$APPLICATION.manifest" ]; then
+    echo -n "Invalid application path specified ($APPLICATION.manifest does not exist). "
+    echo -n "The path should point to application configuration files, so that they can be found "
+    echo    "after appending corresponding extensions."
+    exit 1
 fi
 
 if [ ! -f "$PAL_CMD" ]; then
@@ -118,5 +132,5 @@ fi
 
 CMD=("${ENVS[@]}")
 CMD+=("${PREFIX[@]}")
-CMD+=("$PAL_CMD" "$LIBPAL_PATH" init "$MANIFEST" "$@")
+CMD+=("$PAL_CMD" "$LIBPAL_PATH" init "$APPLICATION" "$@")
 exec env "${CMD[@]}"
