[meson] Add first meson.build for installing
Meson is still optional and not needed to build or run anything. It is
needed only to install Graphene in distro.

Currently only the small subset of what is actually needed is installed:
- graphene and graphene-sgx (for now those are slightly massaged copies
  of pal_loader),
- libpal.so and sgx loader,
- gdb scripts.

Notably manifests should still point trusted_libs to Runtime/ dir in
repo.

diff --git a/Runtime/pal_loader b/Runtime/pal_loader
--- a/Runtime/pal_loader
+++ b/Runtime/pal_loader
@@ -4,61 +4,70 @@
 # Copyright (C) 2019 Invisible Things Lab
 # Copyright (C) 2020 Intel Corporation
 #                    Michał Kowalczyk <mkow@invisiblethingslab.com>
+#                    Wojtek Porczyk <woju@invisiblethingslab.com>
 
-while :
-do
-	case "$1" in
-		"SGX")
-			SGX=1
-			export SGX
-			;;
-		"GDB")
-			GDB=1
-			;;
-		*)
-			break
-			;;
-	esac
-	shift
-done
+if test -n @IN_GIT@  # in meson, this gets zeroed out, so this will only take first branch in repo
+then
+    while :
+    do
+        case "$1" in
+            "SGX")
+                SGX=1
+                export SGX
+                ;;
+            "GDB")
+                GDB=1
+                ;;
+            *)
+                break
+                ;;
+        esac
+        shift
+    done
 
-RUNTIME_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
-if [ -z "$PAL_HOST" ]; then
-    if ! command -v make >/dev/null; then
-        libpal="$RUNTIME_DIR/libpal-*.so"
-        libpal="$(echo -n "$libpal")"
-        libpal="${libpal//$RUNTIME_DIR\//}"
-        if [ "$libpal" = 'libpal-*.so' ]; then
-            echo "Unable to detect PAL_HOST. Please install the make program."
-            exit 1
+    RUNTIME_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+    if [ -z "$PAL_HOST" ]; then
+        if ! command -v make >/dev/null; then
+            libpal="$RUNTIME_DIR/libpal-*.so"
+            libpal="$(echo -n "$libpal")"
+            libpal="${libpal//$RUNTIME_DIR\//}"
+            if [ "$libpal" = 'libpal-*.so' ]; then
+                echo "Unable to detect PAL_HOST. Please install the make program."
+                exit 1
+            fi
+
+            array=("$libpal")
+            if [ ${#array[@]} -ne 1 ]; then
+                echo "Multiple libpal detected ($libpal). Please explicitly set the environment variable PAL_HOST."
+                exit 1
+            fi
+
+            PAL_HOST="${libpal%.so}"
+            PAL_HOST="${PAL_HOST#libpal-}"
+        else
+            PAL_HOST=$(make --no-print-directory --quiet -f "$RUNTIME_DIR/../Scripts/Makefile.configs" print_host 2>&1)
         fi
-
-        array=("$libpal")
-        if [ ${#array[@]} -ne 1 ]; then
-            echo "Multiple libpal detected ($libpal). Please explicitly set the environment variable PAL_HOST."
-            exit 1
-        fi
-
-        PAL_HOST="${libpal%.so}"
-        PAL_HOST="${PAL_HOST#libpal-}"
-    else
-        PAL_HOST=$(make --no-print-directory --quiet -f "$RUNTIME_DIR/../Scripts/Makefile.configs" print_host 2>&1)
     fi
+    PAL_CMD="$RUNTIME_DIR/pal-$PAL_HOST"
+    LIBPAL_PATH=$(realpath "$RUNTIME_DIR/libpal-$PAL_HOST.so")
+    HOST_PAL_PATH=$(realpath "$RUNTIME_DIR/../Pal/src/host/$PAL_HOST")
+else
+    PAL_CMD=@PAL_CMD@
+    LIBPAL_PATH=@LIBPAL_PATH@
+    HOST_PAL_PATH=@HOST_PAL_PATH@
+    SGX=@SGX@
 fi
 
 MANIFEST=
 ENVS=()
 PREFIX=()
-PAL_CMD="$RUNTIME_DIR/pal-$PAL_HOST"
-LIBPAL_PATH=$(realpath "$RUNTIME_DIR/libpal-$PAL_HOST.so")
-HOST_PAL_PATH=$(realpath "$RUNTIME_DIR/../Pal/src/host/$PAL_HOST")
 
 if [ "$GDB" == "1" ]; then
 	PREFIX=("gdb" "-q")
 	if [ -n "$INSIDE_EMACS" ]; then
 		PREFIX+=("-i=mi")
 	fi
-	if [ -v SGX ]; then
+	if [ 0"$SGX" -gt 0 ]; then
 		PREFIX+=("-x" "$HOST_PAL_PATH/gdb_integration/graphene_sgx_gdb.py")
 		ENVS+=("LD_PRELOAD=$HOST_PAL_PATH/gdb_integration/sgx_gdb.so")
 	else
@@ -88,7 +97,7 @@ if [ "$MANIFEST" == "" ]; then
 fi
 
 if [ ! -f "$PAL_CMD" ]; then
-	echo "$PAL_CMD is not built"
+	echo "$PAL_CMD not found"
 	exit 1
 fi
 
