fixup! [Pal/Linux-SGX] tools: add RA-TLS utility libraries

diff --git a/Jenkinsfiles/Linux-SGX-apps b/Jenkinsfiles/Linux-SGX-apps
--- a/Jenkinsfiles/Linux-SGX-apps
+++ b/Jenkinsfiles/Linux-SGX-apps
@@ -129,13 +129,15 @@ pipeline {
                         timeout(time: 5, unit: 'MINUTES') {
                             sh '''
                                 cd Examples/ra-tls-mbedtls
-                                if [ "${ra_client_spid}" != "" ]; then \
+                                if [ "${ra_client_spid}" != "" ] && [ "${ra_client_key}" != "" ]; \
+                                then \
                                     make SGX=1 check_epid RA_CLIENT_SPID=${ra_client_spid} \
                                                           RA_TLS_EPID_API_KEY=${ra_client_key} \
                                                           RA_CLIENT_LINKABLE=0 \
-                                                          RA_TLS_ALLOW_OUTDATED_TCB=1; \
+                                                          RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1; \
                                 else \
-                                    echo "Failure: no ra_client_spid and/or ra_client_key!"
+                                    echo "Failure: no ra_client_spid and/or ra_client_key!" \
+                                    exit 1 \
                                 fi
                             '''
                         }
